### ISSUE TITLE
FC or Pool feature?

### ISSUE THREAD

**Issue by Panpanpie** [mangye16/Cross-Modal-Re-ID-baseline#14]
Excuse me.
I ran the  command `python train.py --dataset sysu --lr 0.1 --method agw --gpu 1` and test on the best epoch(26, just the same as your best epoch), and got `POOL:   Rank-1: 49.60% | mAP: 49.08%` , it's a little better than the model you offered which written in your paper: `POOL:   Rank-1: 47.50% | mAP: 47.65%`
However, when I observe the trainning log , I found the result of FC feature is better than POOL feature, while the test result is opposite：
In the training process：
`Test Epoch: 26
POOL:   Rank-1: 50.30% | Rank-5: 74.78% | Rank-10: 84.09%| Rank-20: 93.87%| mAP: 49.01%| mINP: 35.75%
FC:   Rank-1: 52.33% | Rank-5: 76.49% | Rank-10: 85.64%| Rank-20: 92.85%| mAP: 50.94%| mINP: 37.69%`

In the testing process：
`Test Trial: 0
POOL:   Rank-1: 52.33% | Rank-5: 76.49% | Rank-10: 85.64%| Rank-20: 92.85%| mAP: 50.94%| mINP: 37.69%
FC:   Rank-1: 50.30% | Rank-5: 74.78% | Rank-10: 84.09%| Rank-20: 93.87%| mAP: 49.01%| mINP: 35.75%`

Then I found you use the POOL performance as the FC output in test.py:

`print('FC:   Rank-1: {:.2%} | Rank-5: {:.2%} | Rank-10: {:.2%}| Rank-20: {:.2%}| mAP: {:.2%}| mINP: {:.2%}'.format(
    cmc_pool[0], cmc_pool[4], cmc_pool[9], cmc_pool[19], mAP_pool, mINP_pool))`
So I think you actually used the FC performance which got Rank-1 47.50%. I'm little confused about it. Which one (POOL/FC feature) should be used  in final model evaluation? Or both are OK?

**Comment by mangye16** [comment]
Hi,

You findings are interesting. I think either POOL or FC feature is fine for the final model evaluation. Many existing methods report the accuracies from both layers. 

Thanks.

**Comment by Panpanpie** [comment]
OK, thank you for your reply~^_^
