### ISSUE TITLE
The score of test.py is wrong

### ISSUE THREAD

**Issue by lzw-wo** [mangye16/Cross-Modal-Re-ID-baseline#17]
Hi，Dr.Ye，thanks for your released code，I‘m learning it，but when I run the test.py with model file
`sysu_awg_p4_n8_lr_0.1_seed_0.t`，the result is very low------only 4.15（map） and2（rank-1）， I just change the path of the data and model .Could you please help me to find out why i get the wrong result,Thank you very much!

**Comment by mangye16** [comment]
I suppose you did not correctly load the weights file. You may double-check it.

**Comment by lzw-wo** [comment]
> I suppose you did not correctly load the weights file. You may double-check it.

Thanks for your reply, I'll double-check it.

**Comment by lzw-wo** [comment]
I'm sure it is right ,I load the weights file you released as your way,and I can't realy know why
![image](https://user-images.githubusercontent.com/56921058/98191140-8a6bcf80-1f53-11eb-8d63-567d9b0c6800.png)

**Comment by mangye16** [comment]
Could you please attach a full figure including the model loading output log?

**Comment by lzw-wo** [comment]
> Could you please attach a full figure including the model loading output log?

![image](https://user-images.githubusercontent.com/56921058/98191435-209ff580-1f54-11eb-9d5e-a4bd4f34e50d.png)
![image](https://user-images.githubusercontent.com/56921058/98191451-272e6d00-1f54-11eb-8ede-00f80687c4e9.png)

**Comment by mangye16** [comment]
![image](https://user-images.githubusercontent.com/20569873/98191512-51802a80-1f54-11eb-82ae-86308b793503.png)

**Comment by lzw-wo** [comment]
But I realy put it there
![image](https://user-images.githubusercontent.com/56921058/98191618-8f7d4e80-1f54-11eb-97e9-b9916f1feba9.png)

**Comment by lzw-wo** [comment]
Oh!  I know it, sorry about that, I wrote a global path in `resume`,so no checkpoint found in `model_path`----'save_model/'

**Comment by lzw-wo** [comment]
Thank you very much！

**Comment by mangye16** [comment]
great!

**Comment by vk-rrr** [comment]
> 哦！我知道，很抱歉，我在 中写了一个全局路径，所以在----'save_model/'中找不到检查点`resume``model_path`

请问这个路径应该怎么改？
