### ISSUE TITLE
An interesting phenomenon when testing on RegDB

### ISSUE THREAD

**Issue by Zoky-2020** [mangye16/Cross-Modal-Re-ID-baseline#19]
When testing on RegDB, Rank-1, mAP, mINP seem right in the first round.
But in the next few rounds, the indexes are abnormally high.
![图片](https://user-images.githubusercontent.com/71545908/120338881-35483e80-c327-11eb-9112-1f70356d3ffd.png)

So I checked test.py and found that the test_trial is changing in the testing process, which means that the train-test splitting is different from that of training process.
The images in the training process might be divided into test set if the train-test splitting changed, so the indexes are extremly high.
Is that right?

![图片](https://user-images.githubusercontent.com/71545908/120338724-16e24300-c327-11eb-8f88-e3c66d805706.png)

**Comment by mangye16** [comment]
For RegDB dataset, you need to train 10 different trials, and then evaluate it in ten corresponding trials, i.e., train trial 1 and evaluate test trial 1.

**Comment by Zoky-2020** [comment]
Thank you very much.
