### ISSUE TITLE
Why only id loss can be found in train.py?

### ISSUE THREAD

**Issue by xiezhy6** [mangye16/Cross-Modal-Re-ID-baseline#2]
Hi~ 
Is it the final version?  Why only id loss can be found in train.py?

**Comment by liurongfang** [comment]
> Hi~
> Is it the final version? Why only id loss can be found in train.py?

This is a baseline,I think this repo is not implement all in details,maybe you can see other repo(Visible Thermal ...) by mangye16.

**Comment by maodoudabai** [comment]
hello!How do you implement it with pytorch?Can you open source the code of pytorch version?Thank you very much!!!
