### ISSUE TITLE
What is your python version

### ISSUE THREAD

**Issue by liurongfang** [mangye16/Cross-Modal-Re-ID-baseline#3]
Hello,thanks for your beautiful work!
but I get some error as follow in run your code:
"result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaf in position 0: ordinal not in range(128)"
maybe is beacause of python version,I use Python 3.6 and Pytorch 1.0.1(stable) with CUDA 10.
wait your reply,thanks

**Comment by mangye16** [comment]
hi, my python version is 2.7, pytorch is 0.4 and cuda 8.0.

I think you can easily fix the errors with some minor modifications. Good luck!

**Comment by liurongfang** [comment]
> hi, my python version is 2.7, pytorch is 0.4 and cuda 8.0.
> 
> I think you can easily fix the errors with some minor modifications. Good luck!

Thank you!I am run through this in python 2.7,pytorch 1.0.1 and cuda 8.0,it's ok,good work:).But maybe this code just implement ID loss as a baseline,not all details in paper?and I reading another code(Visble-Thermal-Person-Re-Identification).
