### ISSUE TITLE
The result of the recurrence is incorrect.

### ISSUE THREAD

**Issue by zhangqi2188** [mangye16/Cross-Modal-Re-ID-baseline#4]
Is the number of images in the query smaller than the gallery? Thanks

**Comment by mangye16** [comment]
The number of the query images is 2060 and the gallery is 2060 on the RegDB dataset.
The number of the query image is 3803 and the gallery set contains randomly sampled 301 images (all-search) at each trial on the SYSU-MM01 dataset.

Hope it answers your question.

**Comment by zhangqi2188** [comment]
> The number of the query images is 2060 and the gallery is 2060 on the RegDB dataset.
> The number of the query image is 3803 and the gallery set contains randomly sampled 301 images (all-search) at each trial on the SYSU-MM01 dataset.
> 
> Hope it answers your question.

Thank you, but the map I got on sysu is 4.15%. Can you give me some advice on where to find the reason?

**Comment by zhangqi2188** [comment]
where is the resuming from checkpoint?  Is the sysu_id_bn_relu_drop_0.0_lr_1.0e-02_dim_512_resnet50_best.t ?  thank you very much.

**Comment by zhanqan** [comment]
> where is the resuming from checkpoint? Is the sysu_id_bn_relu_drop_0.0_lr_1.0e-02_dim_512_resnet50_best.t ? thank you very much.

I have encountered the same problem as you. Have you finally solved this problem？

**Comment by zhanqan** [comment]
> > The number of the query images is 2060 and the gallery is 2060 on the RegDB dataset.
> > The number of the query image is 3803 and the gallery set contains randomly sampled 301 images (all-search) at each trial on the SYSU-MM01 dataset.
> > Hope it answers your question.
> 
> Thank you, but the map I got on sysu is 4.15%. Can you give me some advice on where to find the reason?

I have encountered the same problem as you. 
All Average:                                                                                            
FC: top-1: 2.38% | top-5: 9.09% | top-10: 16.34%| top-20: 29.00%                                      
mAP: 4.03%                                                                                              
POOL5: top-1: 2.35% | top-5: 9.48% | top-10: 16.94%| top-20: 29.69%                                     
mAP: 4.16% 
Have you finally solved this problem
