### ISSUE TITLE
no checkpoint found at /home/../save_model/sysu_id_bn_relu_drop_0.0_lr_1.0e-02_dim_512_resnet50_epoch_60.t

### ISSUE THREAD

**Issue by zhangqi2188** [mangye16/Cross-Modal-Re-ID-baseline#5]
no checkpoint found at /home/../save_model/sysu_id_bn_relu_drop_0.0_lr_1.0e-02_dim_512_resnet50_epoch_60.t.    Is this a problem in the training process?

**Comment by mangye16** [comment]
I cannot fully understand your question. Have checked it manually? Did you save the checkpoint in the given path?
