### ISSUE TITLE
RegDB Dataset 

### ISSUE THREAD

**Issue by ThomasKKL** [mangye16/Cross-Modal-Re-ID-baseline#7]
I have no RegDB Dataset，could you give me aprivate download link

**Comment by YYedward** [comment]
The RegDB dataset can not be found in the official link ’http://dm.dongguk.edu/link.html‘
Could you please share this dataset？
email: jungle_hu@sjtu.edu.cn
Thanks！

**Comment by peif1987** [comment]
@liukuixiang @YYedward @mangye16 Hi, Do you guys already get the RegDB dataset ? Could you please also share one copy to me? 
email: fupei1987@163.com
Thanks!

**Comment by ChenSi521** [comment]
@liukuixiang @YYedward @mangye16 @peif1987  Hi, Do you guys already get the RegDB dataset ? Could you please also share one copy to me?
email: 2631706934@qq.com
Thanks!

**Comment by mangye16** [comment]
Please see the guidance in `README` to get the RegDB dataset.

**Comment by Panpanpie** [comment]
Excuse me, I can't find the public version RegDB dataset in the given link, I want to know that can I use this dataset in my research  just by citing the official paper ?   Since there is no way to submit the copyright.

**Comment by mangye16** [comment]
Please see the guidance in `README` to get the RegDB dataset or send me an email.

**Comment by Panpanpie** [comment]
I'am so sorry to bother you again, I have already got the dataset from your given&nbsp;private download link. But I can't find the RegDB in&nbsp;website&nbsp;given in the REDME and can't submit the copyright form. Can I use it in my research without applying for the copyright ? (I'm worry about the copyright)&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mangye16"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 上午9:41
收件人: "mangye16/Cross-Modal-Re-ID-baseline"<Cross-Modal-Re-ID-baseline@noreply.github.com&gt;; 
抄送: "潘与维"<642991922@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [mangye16/Cross-Modal-Re-ID-baseline] RegDB Dataset  (#7)





 
Please see the guidance in README to get the RegDB dataset or send me an email.

**Comment by K0848** [comment]
How do I get the dataset now, not getting results via the readme method
