### ISSUE TITLE
The mode of shot

### ISSUE THREAD

**Issue by L-CODERS** [mangye16/Cross-Modal-Re-ID-baseline#8]
Does this code only perform single-shot result?

**Comment by mangye16** [comment]
Yes, this code only contains the single-shot evaluation protocol.

**Comment by L-CODERS** [comment]
Hi!  I want to ask a question about gallery set. The gallery set contains 301 randomly selected visible images in your paper, but I think there is only 96 visible images in single shot mode and I can't find where indicates the  '301 randomly selected visible images' in the code. Could you tell me how the code implement '301 randomly selected visible images'?

**Comment by mangye16** [comment]
Hi, the random selection is in data_manager.py Line 53-58. In all search mode, it will result in 301 visible (RGB) images.

You can also refer to Ancong's original paper for details.

**Comment by L-CODERS** [comment]
Oh! I'm sorry for my carelessness. Thinks for you reply!
